# Generated by Django 4.1.6 on 2024-08-09 21:21

import mainapp.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название книги')),
                ('author', models.CharField(max_length=50, verbose_name='Автор книги')),
                ('picture', models.ImageField(upload_to='', verbose_name='Обложка книги')),
                ('file_book', models.FileField(upload_to='books/', verbose_name='Файл книги')),
                ('date_of_receipt', models.DateTimeField(verbose_name='Дата получения книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-date_of_receipt'],
            },
            bases=(mainapp.mixins.StrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GenreBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
            bases=(mainapp.mixins.StrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReadBookForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Книгу для чтения',
                'verbose_name_plural': 'Мои книги для чтения',
            },
            bases=(mainapp.mixins.StrMixin, models.Model),
        ),
    ]
