# Generated by Django 4.1.6 on 2024-08-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-date_of_receipt'], 'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='readbookforuser',
            options={'verbose_name': 'Книгу для чтения', 'verbose_name_plural': 'Книги которые читают'},
        ),
        migrations.AlterField(
            model_name='book',
            name='file_book',
            field=models.FileField(upload_to='books/', verbose_name='PDF файл книги'),
        ),
        migrations.AlterField(
            model_name='readbookforuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата получения'),
        ),
    ]
